[Variables]
Vers=1.6.0
; Custom Program Links:
;[Numbers]
3Dmark=steam://rungameid/223850
;[A]
AcrobatReader=%ProgramFiles(x86)%\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
AermemoriesOfOld=steam://rungameid/331870
AlanWake=D:\Program Files (x86)\Steam\steamapps\common\Alan Wake\AlanWake.exe
AllMyTube=%ProgramFiles(x86)%\Wondershare\AllMyTube\WSAllMyTubeSplash.exe
AmongUs=steam://rungameid/945360
AorusEngine=%ProgramFiles(x86)%\GIGABYTE\AORUS ENGINE\Launcher.exe
Arduino=%ProgramFiles(x86)%\Arduino\arduino.exe
AssassinsCreedBrotherhood=steam://rungameid/48190
AssassinsCreedOrigins=steam://rungameid/582160
AssassinsCreedOdyssey=steam://rungameid/812140
AssassinsCreed3Remastered=steam://rungameid/911400
AStoryAboutMyUncle=steam://rungameid/278360
Atomega=steam://rungameid/619880
Audiacity=%UserProfile%\Audacity\Audacity\audacity.exe
Anno1404=steam://rungameid/33250
;[B]
Badland=steam://rungameid/269670
BabaIsYou=steam://rungameid/736260
Beamng=steam://rungameid/284160
Beispiel=taskmng.exe
BioShock=steam://rungameid/7670
BioShock2=steam://rungameid/8850
BorderLands2=steam://rungameid/49520
Braid=steam://rungameid/26800
BattleDotNet=%ProgramFiles(x86)%\Battle.net\Battle.net Launcher.exe
;[C]
Carrion=steam://rungameid/953490
CCleaner=%ProgramFiles%\CCleaner\CCleaner64.exe
CheatEngine=%ProgramFiles%\Cheat Engine 7.0\cheatengine-x86_64.exe
Chrome=%ProgramFiles(x86)%\Google\Chrome\Application\chrome.exe
CitiesSkylines=steam://rungameid/255710
CivilizationV=steam://rungameid/8930
Cms18=steam://rungameid/645630
CallOfDutyModernWarfare=%ProgramFiles(x86)%\Call of Duty Modern Warfare\Modern Warfare Launcher.exe
Control=
CoreTemp=%ProgramFiles%\Core Temp\Core Temp.exe
ControllerCompanion=steam://rungameid/367670
CssGridBuilder=%ProgramFiles%\CoffeeCup Software\CSS Grid Builder\CSS Grid Builder.exe
Collisions=steam://rungameid/390910
Cyberpunk2077=steam://rungameid/1091500
;[D]
Dashlane=%AppData%\Dashlane\Dashlane.exe
DeepL=%LocalAppData%\DeepL\DeepL.exe
Deployment=steam://rungameid/755980
DeusexHumanRevolution=steam://rungameid/28050
DevcPP=%ProgramFiles(x86)%\Dev-Cpp\devcpp.exe
Deiland=steam://rungameid/760620
DigitalSimulator=%ProgramFiles(x86)%\DigitalSimulatorV5.57\DigitalSimulator.exe
Discord=C:\Tools\Scripts\RunNewestDiscord.bat
DieSiedlerOnline=C:\Users\%UserName%\Documents\My Games\The Settlers Online\nw.exe
DogsOfWar=steam://rungameid/219700
DragonCenter=%ProgramFiles(x86)%\MSI\Dragon Center\DragonCenter.exe
Drawful2=steam://rungameid/442070
DynamiteJack=%ProgramFiles(x86)%\Dynamite Jack\Dynamite Jack.exe
;[E]
Eagle=D:\EAGLE 9.0.0\eagle.exe
Edge=steam://rungameid/38740
Evoland=steam://rungameid/1020470
Exapunks=steam://rungameid/716490
Exel=%ProgramFiles%\Microsoft Office\root\Office16\EXCEL.EXE
EnvironmentalStationAlpha=steam://rungameid/350070
;[F]
Firefox=%ProgramFiles%\Mozilla Firefox\firefox.exe
FixWin10=C:\Windows_Repair_Toolbox\Downloads\FixWin10\FixWin 10.0.1.0\FixWin 10.exe
Flower=steam://rungameid/966330
FrostPunk=steam://rungameid/323190
FtbLauncher=%UserProfile%\AppData\Roaming\ftblauncher\FTB_Launcher.exe
Funktions=%ProgramData%\Microsoft\Windows\Start Menu\Programs\System Tools\Geheimer Dateiexplorer.lnk
FARLoneSails=steam://rungameid/609320
;[G]
GanttProject=%ProgramFiles(x86)%\GanttProject-2.8\ganttproject.exe
GeforceExperience=%ProgramFiles%\NVIDIA Corporation\NVIDIA GeForce Experience\NVIDIA GeForce Experience.exe
GeoGebra=%LocalAppData%\GeoGebra_Graphing\Update.exe
GetProgramms=Shell:AppsFolder
GoatSimulator=steam://rungameid/265930
Godus=steam://rungameid/232810
GodusWars=steam://rungameid/422420
Gomoku=https://gomokuonline.com/
GravNewton=steam://rungameid/549100
GtaV=steam://rungameid/271590
GreedFall=steam://rungameid/606880
GitBash=%LocalAppData%\Programs\Git\git-bash.exe --cd-to-home
;[H]
Hacknet=steam://rungameid/365450
HardspaceShipbreaker=steam://rungameid/1161580
HideDotMeVPN=%ProgramFiles(x86)%\hide.me VPN\Hide.me.exe
HumanFallFlat=steam://rungameid/477160
;[I]
IntelExtremeTuningUtility=%Public%\Desktop\Intel(R) Extreme Tuning Utility.lnk
IrfanView=%ProgramFiles%\IrfanView\i_view64.exe
IrfanViewThumbnails=#IrfanView# /thumbs
Islanders=steam://rungameid/1046030
;[J]
JustCause1=steam://rungameid/6880
JustCause2=steam://rungameid/8190
JustCause3=steam://rungameid/225540
JustCause4=steam://rungameid/517630
;[K]
KeePass2=%ProgramFiles(x86)%\KeePass Password Safe 2\KeePass.exe
Kies3=C:\Program Files (x86)\Samsung\Kies3\Kies3.exe
;[L]
LegoWorlds=steam://rungameid/332310
LMMS=%ProgramFiles%\LMMS\lmms.exe
LOL=C:\Riot Games\Riot Client\RiotClientServices.exe
;[M]
McEdit2=D:\Spiele Addons\MCedit 2 win64 beta11\mcedit2.exe
McModInstaller=%AppData%\Modinstaller\MCModinstaller.exe
Mechanism=steam://rungameid/645290
Metro2033=steam://rungameid/43110
Minecraft=%AppData%\.minecraft\Minecraft.exe
MinionMasters=steam://rungameid/489520
MicrosoftTeams=%LocalAppData%\Microsoft\Teams\Update.exe --processStart "Teams.exe"
MorphvoxPro=D:\Program Files (x86)\Steam\steamapps\common\MorphVOX Pro\MorphVOXPro.exe
Mpchc=%ProgramFiles%\MPC-HC\mpc-hc64.exe
MsiAppPlayer=%ProgramFiles%\BlueStacks_msi2\Client\BlueStacks.exe
MsiMysticLight=%ProgramFiles(x86)%\MSI\MysticLight\SMysticLight.exe
MyPhoneExplorer=%ProgramFiles(x86)%\MyPhoneExplorer\MyPhoneExplorer.exe
;[N]
NeedForSpeed=D:\Program Files (x86)\Origin Games\Need for Speed\NFS16.exe
NeedForSpeedMostWanted=D:\Program Files (x86)\Origin Games\Need for Speed(TM) Most Wanted\NFS13.exe
NeedForSpeedHeat=steam://rungameid/1222680
NierAutomata=steam://rungameid/524220
NightSkyHd=D:\Program Files (x86)\NightSkyHD\NightSkyHD_Win_1217\NightSkyHD.exe
NoMansSky=steam://rungameid/275850
NotepadPP=%ProgramFiles%\Notepad++\notepad++.exe
Noita=steam://rungameid/881100
NoitaDev=D:\Program Files (x86)\Steam\steamapps\common\Noita\noita_dev.exe
;[O]
OBSStudio=%ProgramFiles%\obs-studio\bin\64bit\obs64.exe
Ordner1=D:\Downloads
Ordner1_Titel=Downloads
Ordner1_Info=Heruntergeladene Dateien, Programme
Ordner2=%UserProfile%\Documents\Rainmeter\Skins\Fantastic Desktop\Extra Icons
Ordner2_Titel=Fantastic Desktop
Ordner2_Info=Extra Icons: Verzeichnis
Ordner3=%UserProfile%\Documents\Rainmeter\Skins\Neon Space\@Resources\Images\Extra Icons
Ordner3_Titel=Fantastic Desktop
Ordner3_Info=Extra Icons: Grafiken
Ordner4=%UserProfile%\Documents\Bluetooth
Ordner4_Titel=Bluetooth
Ordner4_Info=#CRLF#
Origin=%ProgramFiles(x86)%\Origin\Origin.exe
Osmos=steam://rungameid/29180
OracleVMVirtualBox=%ProgramFiles%\Oracle\VirtualBox\VirtualBox.exe
OriAndTheWillOfTheWisps=steam://rungameid/1057090
;[P]
Paintnet=%ProgramFiles%\paint.net\PaintDotNet.exe
ParallelsCross=steam://rungameid/456980
PolyBridge=steam://rungameid/367450
PowerPoint=%ProgramFiles%\Microsoft Office\root\Office16\POWERPNT.EXE
PUPG=steam://rungameid/578080
PDF24=%ProgramFiles(x86)%\PDF24\pdf24-Launcher.exe
Portal=steam://rungameid/400
Portal2=steam://rungameid/620
;[Q]
QuakeChampions=steam://rungameid/611500
;[R]
RgbFusion20=%ProgramFiles(x86)%\GIGABYTE\RGBFusion\RGBFusion.exe
RingsOfSaturn=steam://rungameid/846030
RoccatSwarm=%ProgramFiles(x86)%\ROCCAT\ROCCAT Swarm\ROCCAT_Swarm.exe
;[S]
ShadowOfTheTombraider=steam://rungameid/750920
ShareX=steam://rungameid/400040
Skype=%ProgramFiles(x86)%\Skype\Phone\Skype.exe
SniperGhostWarriorContract=steam://rungameid/973580
Solar2=steam://rungameid/97000
MicrosoftSolitairCollection=D:\StartVerknuepfungen\Microsoft Solitaire Collection.lnk
Steam=D:\Program Files (x86)\Steam\Steam.exe
Steep=steam://rungameid/460920
Subnautica=steam://rungameid/264710
Sumoman=steam://rungameid/552970
Spotify=C:\Tools\Shortcuts\Spotify.lnk
System=
SystemIcons=Shell:::{05d7b0f4-2121-4eff-bf6b-ed3f69b894d9}
StickyPassword=%ProgramFiles(x86)%\Sticky Password\stpass.exe
SuperbrothersSwordAndSworceryEP=steam://rungameid/204060
ShellShockLive=steam://rungameid/326460
;[T]
TansportFever2=steam://rungameid/1066780
Teardown=steam://rungameid/1167630
Teamspeak=%LocalAppData%\TeamSpeak 3 Client\ts3client_win64.exe
TechnicLauncher=%AppData%\.technic\TechnicLauncher.exe
TechSupportErrorUnknown=steam://rungameid/781480
TerraTech=steam://rungameid/285920
TheCrew2=steam://rungameid/646910
TheOrionSuns=steam://rungameid/787570
TheSecretsOfTheForest=steam://rungameid/822770
TheSims3=steam://rungameid/47890
TheSwapper=steam://rungameid/231160
TheTechnomancer=steam://rungameid/338390
TheWitcher3=steam://rungameid/292030
Thunderbird=%ProgramFiles%\Mozilla Thunderbird\thunderbird.exe
TorBrowser=D:\Tools\Tor Browser\Browser\firefox.exe
TransportFever=steam://rungameid/446800
Twitch=https://www.twitch.tv/
Twitch_Acc1=https://www.twitch.tv/dascold
;[U]
Uboat=steam://rungameid/494840
UnityEditor=%ProgramFiles%\Unity\Hub\Editor\2019.4.10f1\Editor\Unity.exe
UnityHub=%ProgramFiles%\Unity Hub\Unity Hub.exe
Uplay=%ProgramFiles(x86)%\Ubisoft\Ubisoft Game Launcher\Uplay.exe
;[V]
Vessel=%ProgramFiles(x86)%\Vessel\Vessel.exe
VisualStudioCode=%LocalAppData%\Programs\Microsoft VS Code\Code.exe
VLC=%ProgramFiles%\VideoLAN\VLC\vlc.exe
VRchat=steam://rungameid/438100
VRmark=steam://rungameid/464170
VirtualBox=%ProgramFiles%\Oracle\VirtualBox\VirtualBox.exe
;[W]
WallpaperEngine=steam://rungameid/431960
WatchDogs=steam://rungameid/243470
WatchDogs2=steam://rungameid/447040
WhenTheyArrived=steam://rungameid/843860
WhileTrueLearn=steam://rungameid/619150
Word=%ProgramFiles%\Microsoft Office\root\Office16\WINWORD.EXE
WorldPainter=%LocalAppData%\Programs\WorldPainter\worldpainter.exe
WormsWMD=steam://rungameid/327030
WorldOfTanks=D:\Games\World_of_Tanks\WoTLauncher.exe
WorldOfWarships=D:\Games\World_of_Warships\WoWSLauncher.exe
Wreckfest=steam://rungameid/228380
WolfQuest=steam://rungameid/431180
WolfQuestAnniversaryEdition=steam://rungameid/926990
;[X]
;[Y]
Ylands=steam://rungameid/298610
;[Z]

Glink1=VLC.exe
Glink2=C:\Users\%UserName%
Glink3=::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
Glink4=::{450D8FBA-AD25-11D0-98A8-0800361B1103}
Glink5=Firefox.exe
Glink6=Photoshop.exe

Gname1=VLC
Gname2=%1
Gname3=Computer
Gname4=Documents
Gname5=Firefox
Gname6=Photoshop

Ilink1=%ProgramFiles%\LMMS\lmms.exe
Ilink2=C:\Users\%UserName%\AppData\Local\TeamSpeak 3 Client\ts3client_win64.exe
Ilink3=C:\Users\%UserName%\Audacity\Audacity\audacity.exe
Ilink4=%ProgramFiles(x86)%\Skype\
Ilink5=%ProgramFiles(x86)%\ffmpegyag\bin\ffmpegyag.exe
Ilink6=D:\Downloads\MPC-HC.1.7.10.x64\MPC-HC.1.7.10.x64\mpc-hc64.exe

Iname1=Link 1
Iname2=Link 2
Iname3=Link 3
Iname4=Link 4
Iname5=Link 5
Iname6=Link 6

;Cut-Links
CutA=::{450D8FBA-AD25-11D0-98A8-0800361B1103}
CutB=::{59031a47-3f72-44a7-89c5-5595fe6b30ee}
Cutc=::{645FF040-5081-101B-9F08-00AA002F954E}
CutD=::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}
CutE=::{374DE290-123F-4565-9164-39C4925E467B}
CutF=::{B4BFCC3A-DB2C-424C-B029-7FE99A87C641}

;Cut-Link Description
CutName1=FACEBOOK
CutName2=User's Profile
CutName3=Recycle Bin
CutName4=Control Panel
CutName5=Downloads
CutName6=Desktop

;System-Links
SysLink1=::{D20EA4E1-3957-11d2-A40B-0C5020524153}
SysLink2=::{4234d49b-0245-4df3-b780-3893943456e1}
SysLink3=::{28803F59-3A75-4058-995F-4EE5503B023C}
SysLink4=::{437ff9c0-a07f-4fa0-af80-84b6c6440a16}
SysLink5=::{5399E694-6CE5-4D6C-8FCE-1D8870FDCBA0}
SysLink6=::{1206F5F1-0569-412C-8FEC-3204630DFB70}
SysLink7=::{17cd9488-1228-4b2f-88ce-4298e93e0966}
SysLink8=::{74246bfc-4c96-11d0-abef-0020af6b0b7a}
SysLink9=::{C555438B-3C23-4769-A71F-B6D3D9B6053A}
SysLink10=::{15eae92e-f17a-4431-9f28-805e482dafd4}
SysLink11=::{2559a1f1-21d7-11d4-bdaf-00c04f60b9f0}
SysLink12=
SysLink13=
SysLink14=
SysLink15=
SysLink16=
SysLink17=

;System-Link Descriptions
SysDesc1=Administrative Tools
SysDesc2=Applications
SysDesc3=Bluetooth
SysDesc4=Command Folder
SysDesc5=Control Panel
SysDesc6=Credential Manager
SysDesc7=Default Programs
SysDesc8=Device Manager
SysDesc9=Display
SysDesc10=Get Programs
SysDesc11=Help and Support
SysDesc12=
SysDesc13=
SysDesc14=
SysDesc15=
SysDesc16=
SysDesc17=

; ------------------------- GROUP-Links ------------------------------------------- (Testphase)
Group_Medien1=\lmms
Group_Medien2=\wallpaperengine
Group_Medien3=allmytube
Group_Medien4=obsstudio
Group_Medien5=mpchc
Group_Medien6=skype
Group_Medien7=vlc
Group_Medien8=keepass2
Group_Medien9=kies3
Group_Medien10=audiacity
Group_Medien11=teamspeak
Group_Medien12=morphvoxpro
Group_Medien13=msiappplayer