[Variables]

Shortcut1=C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\Uplay.exe
Shortcut2=D:\Program Files (x86)\Origin\Origin.exe
Shortcut3=D:\Program Files (x86)\Steam\Steam.exe
Shortcut4=D:\Program Files (x86)\GameforgeLive\GameforgeLive.exe

Font1=Gliscor Gothic
Font2=Myriad Pro
Font3=Ebrima
Font4=Digital
Font5=Cambria
Font6=Arial
Font7=Segoe UI
Font8=Impact

Global_DelayA=150
Global_DelayB=500

Group_MouseOver=1

Drive1=C:
Drive2=D:
Drive3=F:
Drive4=G:
DownMax = 1048576
UpMax =1048576

Flare1=0
Flare=1

Format="%I"
Format2="%I:%M"
Hour=H

Path1=C:\Program Files (x86)\LibreOffice 5\program\soffice.exe
Path1Name=LibreOffice

Path2=C:\Program Files\GIMP 2\bin\gimp-2.8.exe
Path2Name=GIMP 2

Path3=C:\Program Files (x86)\KeePass Password Safe 2\KeePass.exe
Path3Name=KeePass

Path4=D:\Program Files (x86)\Tor Browser\Browser\firefox.exe
path4Name=Tor Browser

Path5=C:\Program Files\Mozilla Firefox\firefox.exe
Path5Name=Firefox

Llink1=C:\Program Files (x86)\Mozilla Thunderbird\thunderbird.exe
Llink2=D:\Filme\Captures
Llink3=D:\Share
Llink4=D:\Hilfetools

Link1=steam://rungameid/447040
Link2=D:\Games\World_of_Tanks\WorldOfTanks.exe
Link3=C:\Users\%USERNAME%\AppData\Roaming\.minecraft\Minecraft.exe
Link4=steam://rungameid/232810
Link5=D:\Downloads

Name1=WD2
Name2=WoT
Name3=Minecraft
Name4=Godus

;-----------------------------------------ExtraIcons----------------------------------------------

;EName1=Dev C++
EILink1="C:\Program Files (x86)\Dev-Cpp\devcpp.exe"
;EName2=Vessel
EILink2="C:\Program Files (x86)\Vessel\Vessel.exe"
;EName3=All My Tube
EILink3="D:\Share\Wondershare AllMyTube.lnk"
;EName4=Atomega
EILink4=steam://rungameid/619880
;EName5=Osmos
EILink5=steam://rungameid/29180
;EName6=Transport Fever
EILink6=steam://rungameid/446800
;EName7=BeamNG.Drive
EILink7=steam://rungameid/284160
;EName8=Minecraft
EILink8=C:\Users\%USERNAME%\AppData\Roaming\.minecraft\Minecraft.exe
;EName9=Origin
EILink9=D:\Program Files (x86)\Origin\Origin.exe
;EName10=Uplay - Ubisoft
EILink10=C:\Program Files (x86)\Ubisoft\Ubisoft Game Launcher\Uplay.exe
;EName11=Steam
EILink11=D:\Program Files (x86)\Steam\Steam.exe
;EName12=Terra Tech
EILink12=steam://rungameid/285920
;EIName13=
EILink13=
;EIName14=Twitch
EILink14=https://www.twitch.tv/
;EIName15=Discord
EILink15=C:\Users\%USERNAME%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Discord Inc\Discord.lnk
;EIName16=VR Chat
EILink16=steam://rungameid/438100
;EIName17=Assasins Creed: Origins
EILink17=steam://rungameid/582160

Hour=I

NeonLightName=Images/Visualisers/Neonlights/2ray
NeonLightName2=Images/Visualisers/Neonlights/2ray2

NeonLightPers=Images/Perspective/p
NeonLightPers2=Images/Perspective/pr

Circle=Lines

MusicPlayer=WMP
